words:
    - Thank
    - Thanks
    - Спасибо
    - thank
    - thanks
    - спасибо
    - спс
    - СПС
    - Спс
    - THX
    - TNX
    - Thx
    - thx
    - Tnx
    - tnx
messages:
    selfThanks: "*@{username} selflike? How vulgar!*"
    thanks: "*Thanks (+1) to @{receiver}* accepted! Now his carma **{carma}**.*"