minTimeBetweenThanks: 60 # in seconds
words:
    - thank
    - thanks
    - спасибо
    - спс
    - tnx
messages:
    selfThanks: "*@{username} selflike? How vulgar!*"
    thanks: "*Thanks (+1) to @{receiver} accepted! Now his carma **{carma}**.*"
    tooSoon: "You tried to change @{receiver} carma too often. Canceling."